version: '3'

includes:
  external:
    taskfile: ./external/Taskfile.yml
    dir: ./external

tasks:
  main-build:
    desc: Main build task
    cmds:
      - echo "Main building..."

  main-test:
    desc: Main test task
    cmds:
      - echo "Main testing..."