version: '3'

includes:
  nested: ./nested

tasks:
  build:
    desc: Build the project
    cmds:
      - echo "Building..."

  test:
    desc: Run tests
    cmds:
      - echo "Testing..."

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "Cleaning..."