version: '3'

tasks:
  build:
    desc: Build Docker image
    cmds:
      - echo "Building Docker image"

  run:
    desc: Run Docker container
    cmds:
      - echo "Running Docker container"

  clean:
    desc: Clean Docker resources
    cmds:
      - echo "Cleaning Docker resources"