version: '3'

tasks:
  hello:
    desc: Say hello
    cmds:
      - echo "Hello from Task!"

  build:
    desc: Build the project
    cmds:
      - echo "Building project..."
      - echo "Build complete!"

  test:
    desc: Run tests
    cmds:
      - echo "Running tests..."
      - go test ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "Cleaning..."
      - rm -rf dist/