#!/usr/bin/env -S just --justfile

test:
  cargo test --all

[group: 'misc']
run message:
  echo "run {{message}}"

run2 message1 message2:
  echo "run {{message1}} {{message2}}"

[group: 'misc']
build:
  echo build

[group: 'misc']
fmt : # https://example.com
  echo fmt

[group: 'misc']
[private ]
fmt-private:
  echo fmt

# everyone's favorite animate paper clip
[group: 'check']
clippy:
  echo clippy
