# This workflow is managed by gh actions-lock.

name: Run cargo publish

on:
  push:
    tags: 
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: rust-lang/crates-io-auth-action@v1.0.5
        id: auth
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
