name: GitHub Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  upload-assets:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            archive: fzf-make_$tag_linux_arm64
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            archive: fzf-make_$tag_linux_amd64
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: taiki-e/upload-rust-binary-action@f0d45ae91ee7b8ee928de7a9d04d893a08bcbec6 # v1.30.2
        with:
          bin: fzf-make
          target: ${{ matrix.target }}
          archive: ${{ matrix.archive }}
          token: ${{ secrets.GITHUB_TOKEN }}
