on:
  push:
  pull_request:

jobs:
  env-file-test:
    name: env-file-test
    runs-on: ubuntu-latest
    steps:
      - name: Extract version(original)
        id: extract-version-original
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"

      - name: Extract version(using env files)
        id: extract-version-env-files
        run: |
          echo "tag-name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: echo
        run: |
          echo ${{ steps.extract-version-original.outputs.tag-name }}
          echo ${{ steps.extract-version-env-files.outputs.tag-name }}
